name = "Parsa Hugo"
license = "MIT"
licenselink = "https://github.com/themefisher/parsa-hugo/blob/master/LICENSE"
description = "Hugo port of the Themefisherâ€™s Parsa Template"
homepage = "https://gethugothemes.com/products/parsa-hugo-theme/"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'resume', 'portfolio', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'theme', 'typography']
features = ['bootstrap','responsive']
min_version = "0.58.0"

[author]
  name = "Themefisher"
  homepage = "https://themefisher.com/"