baseurl = "https://attreq-blog.netlify.com"
googleAnalytics = ""
languageCode = "en-us"
paginate = 6
summaryLength = "10"
theme = "parsa-hugo"
title = "ATTREQ Blog | Amazing Outfits, Flamboyant Wardrobes, Mindful Comsumption, Mind-boggling Inspiration, Fashion News and more"
[[menu.main]]
name = "Instagram"
parent = "Follow Us!"
url = "instagram.com/heyattreq"
weight = 1
[[menu.main]]
name = "LinkedIn"
parent = "Follow Us!"
url = "https://linkedin.com/company/attreq"
weight = 2
[[menu.main]]
hasChildren = true
name = "Follow Us!"
weight = 3
[[menu.main]]
name = "Contact"
url = "attreq.com/index.html#contact"
weight = 2
[[menu.main]]
name = "About"
url = "attreq.com/about.html"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
address = "6 rip carl Avenue CA 90733"
author = "John Doe"
author_image = "images/banner-img.png"
bio = "Iâ€™m a Freelance Interactive Art Director based in France. Focusing across branding and identity, digital and print."
contact_form_action = "#"
copyright = "Copyright &copy; 2020 a theme by [themefisher.com](themefisher.com)"
description = "This is meta description"
email = "exmaple@ymail.com"
home = "Home"
layout = "1"
logo = "images/logo.png"
mobile = "+90 000 333 22"
preloader = true
search = true
[params.cookies]
enable = true
expire_days = 2
[params.instafeed]
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"
enable = true
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.social]]
icon = "ti-facebook"
link = "https://facebook.com/themefisher"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
[[params.social]]
icon = "ti-github"
link = "#"
