baseURL = "https://foodie-quarantine.netlify.com"
languageCode = "en-us"
paginate = 6
<<<<<<< HEAD
DefaultContentLanguage = "en"

# output
=======
summaryLength = "10"
theme = "parsa-hugo"
title = "Foodie In Quarantine"
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3
>>>>>>> 0dec695850c41d6f66e11efdd26a02bbd8aed9d1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
address = "6 rip carl Avenue CA 90733"
author = "Raquel"
author_image = "images/banner-img.png"
bio = "Iâ€™m XXXX"
contact_form_action = "#"
copyright = "Copyright &copy; 2020 a theme by [themefisher.com](themefisher.com)"
description = "This is meta description"
email = "???@??.com"
google_analitycs_id = "Your ID"
home = "Home"
layout = "1"
logo = "images/logo.png"
mobile = "XXXX"
preloader = true
search = true
[params.instafeed]
access_token = "4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17"
enable = true
user_id = "4044026246"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.social]]
URL = "#"
icon = "ti-facebook"
[[params.social]]
URL = "#"
icon = "ti-twitter-alt"
[[params.social]]
URL = "#"
icon = "ti-linkedin"
[[params.social]]
URL = "#"
icon = "ti-github"
URL = "#"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"

################################ Spanish Language ########################
[Languages.es]
languageName = "Es"
languageCode = "es-es"
contentDir = "content/spanish"
weight = 2
home = "Hogar"
